package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.17
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("routes",
                                              "Used to perform route transcations",
                                              "https://oasxte7o08.execute-api.us-east-1.amazonaws.com/Development",
                                              new String[] {
                                                  "/createRoute",
                                                  "/getRoute",
                                                  "/useRoute",
                                                  "/createRoute/123",
                                                  "/getRoute/123",
                                                  "/useRoute/123",
                                              },
                                              com.amazonaws.mobile.api.idoasxte7o08.RoutesMobileHubClient.class),
                new CloudLogicAPIConfiguration("bikers",
                                              "manipulate bikers",
                                              "https://orhwiee02g.execute-api.us-east-1.amazonaws.com/Development",
                                              new String[] {
                                                  "/createUser",
                                                  "/verifyUser",
                                                  "/createUser/123",
                                                  "/verifyUser/123",
                                              },
                                              com.amazonaws.mobile.api.idorhwiee02g.BikersMobileHubClient.class),
        };

        return apis;
    }
}
